# Generated by Django 5.0.6 on 2025-09-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('it', 'IT'), ('business', 'Business'), ('language', 'Language'), ('administration', 'Administration')], default='it', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasuser',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
