# Generated by Django 4.2.7 on 2025-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasadminprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='tasuser',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='staff', max_length=20),
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TASAdminProfile',
        ),
    ]
