# Generated by Django 5.0.6 on 2025-09-26 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(choices=[('FaBuilding', 'Building'), ('FaCalendarAlt', 'Calendar'), ('FaUsers', 'Users'), ('FaGraduationCap', 'Graduation Cap'), ('FaBook', 'Book'), ('FaImages', 'Images'), ('FaHeart', 'Heart'), ('FaStar', 'Star'), ('FaTrophy', 'Trophy'), ('FaMicrophone', 'Microphone'), ('FaCamera', 'Camera'), ('FaVideo', 'Video'), ('FaMusic', 'Music'), ('FaGamepad', 'Gamepad'), ('FaFootball', 'Football'), ('FaSwimmingPool', 'Swimming Pool'), ('FaCar', 'Car'), ('FaPlane', 'Plane'), ('FaGlobe', 'Globe'), ('FaMapMarkerAlt', 'Map Marker'), ('FaHome', 'Home'), ('FaSchool', 'School'), ('FaUniversity', 'University'), ('FaLaptop', 'Laptop'), ('FaDesktop', 'Desktop'), ('FaTablet', 'Tablet'), ('FaMobile', 'Mobile'), ('FaWifi', 'WiFi'), ('FaCog', 'Settings'), ('FaTools', 'Tools'), ('FaLightbulb', 'Lightbulb'), ('FaRocket', 'Rocket'), ('FaGem', 'Gem'), ('FaCrown', 'Crown'), ('FaMedal', 'Medal'), ('FaAward', 'Award'), ('FaCertificate', 'Certificate'), ('FaScroll', 'Scroll'), ('FaBookOpen', 'Book Open'), ('FaPen', 'Pen'), ('FaPencil', 'Pencil'), ('FaEraser', 'Eraser'), ('FaCalculator', 'Calculator'), ('FaRuler', 'Ruler'), ('FaCompass', 'Compass'), ('FaMicroscope', 'Microscope'), ('FaFlask', 'Flask'), ('FaAtom', 'Atom'), ('FaDna', 'DNA'), ('FaLeaf', 'Leaf'), ('FaTree', 'Tree'), ('FaSun', 'Sun'), ('FaMoon', 'Moon'), ('FaCloud', 'Cloud'), ('FaRainbow', 'Rainbow'), ('FaSnowflake', 'Snowflake'), ('FaFire', 'Fire'), ('FaWater', 'Water'), ('FaWind', 'Wind'), ('FaMountain', 'Mountain'), ('FaSea', 'Sea'), ('FaFish', 'Fish'), ('FaBird', 'Bird'), ('FaCat', 'Cat'), ('FaDog', 'Dog'), ('FaHorse', 'Horse'), ('FaPaw', 'Paw'), ('FaBug', 'Bug'), ('FaSpider', 'Spider'), ('FaButterfly', 'Butterfly'), ('FaFlower', 'Flower'), ('FaSeedling', 'Seedling'), ('FaApple', 'Apple'), ('FaBanana', 'Banana'), ('FaCarrot', 'Carrot'), ('FaPizza', 'Pizza'), ('FaHamburger', 'Hamburger'), ('FaCoffee', 'Coffee'), ('FaTea', 'Tea'), ('FaBeer', 'Beer'), ('FaWine', 'Wine'), ('FaCake', 'Cake'), ('FaCookie', 'Cookie'), ('FaIceCream', 'Ice Cream'), ('FaCandy', 'Candy'), ('FaGift', 'Gift'), ('FaBirthdayCake', 'Birthday Cake'), ('FaPartyHorn', 'Party Horn'), ('FaBalloon', 'Balloon'), ('FaConfetti', 'Confetti'), ('FaFireworks', 'Fireworks'), ('FaMagic', 'Magic'), ('FaWand', 'Wand'), ('FaHat', 'Hat'), ('FaMask', 'Mask'), ('FaGlasses', 'Glasses'), ('FaEye', 'Eye'), ('FaEar', 'Ear'), ('FaNose', 'Nose'), ('FaMouth', 'Mouth'), ('FaHand', 'Hand'), ('FaFist', 'Fist'), ('FaThumbsUp', 'Thumbs Up'), ('FaThumbsDown', 'Thumbs Down'), ('FaPeace', 'Peace'), ('FaOk', 'OK'), ('FaPointUp', 'Point Up'), ('FaPointDown', 'Point Down'), ('FaPointLeft', 'Point Left'), ('FaPointRight', 'Point Right'), ('FaStop', 'Stop'), ('FaPlay', 'Play'), ('FaPause', 'Pause'), ('FaForward', 'Forward'), ('FaBackward', 'Backward'), ('FaStepForward', 'Step Forward'), ('FaStepBackward', 'Step Backward'), ('FaFastForward', 'Fast Forward'), ('FaFastBackward', 'Fast Backward'), ('FaShuffle', 'Shuffle'), ('FaRepeat', 'Repeat'), ('FaVolumeUp', 'Volume Up'), ('FaVolumeDown', 'Volume Down'), ('FaVolumeMute', 'Volume Mute'), ('FaVolumeOff', 'Volume Off'), ('FaHeadphones', 'Headphones'), ('FaMicrophoneAlt', 'Microphone Alt'), ('FaRadio', 'Radio'), ('FaTv', 'TV'), ('FaPhone', 'Phone'), ('FaFax', 'Fax'), ('FaEnvelope', 'Envelope'), ('FaMailBulk', 'Mail Bulk'), ('FaInbox', 'Inbox'), ('FaOutbox', 'Outbox'), ('FaArchive', 'Archive'), ('FaTrash', 'Trash'), ('FaRecycle', 'Recycle'), ('FaSave', 'Save'), ('FaDownload', 'Download'), ('FaUpload', 'Upload'), ('FaShare', 'Share'), ('FaLink', 'Link'), ('FaUnlink', 'Unlink'), ('FaCopy', 'Copy'), ('FaCut', 'Cut'), ('FaPaste', 'Paste'), ('FaUndo', 'Undo'), ('FaRedo', 'Redo'), ('FaSearch', 'Search'), ('FaFilter', 'Filter'), ('FaSort', 'Sort'), ('FaSortUp', 'Sort Up'), ('FaSortDown', 'Sort Down'), ('FaList', 'List'), ('FaTh', 'Grid'), ('FaThList', 'Grid List'), ('FaBars', 'Bars'), ('FaEllipsisH', 'Ellipsis Horizontal'), ('FaEllipsisV', 'Ellipsis Vertical'), ('FaPlus', 'Plus'), ('FaMinus', 'Minus'), ('FaTimes', 'Times'), ('FaCheck', 'Check'), ('FaExclamation', 'Exclamation'), ('FaQuestion', 'Question'), ('FaInfo', 'Info'), ('FaExclamationTriangle', 'Exclamation Triangle'), ('FaQuestionCircle', 'Question Circle'), ('FaInfoCircle', 'Info Circle'), ('FaCheckCircle', 'Check Circle'), ('FaTimesCircle', 'Times Circle'), ('FaBan', 'Ban'), ('FaLock', 'Lock'), ('FaUnlock', 'Unlock'), ('FaKey', 'Key'), ('FaShield', 'Shield'), ('FaShieldAlt', 'Shield Alt'), ('FaUser', 'User'), ('FaUserAlt', 'User Alt'), ('FaUserCheck', 'User Check'), ('FaUserTimes', 'User Times'), ('FaUserPlus', 'User Plus'), ('FaUserMinus', 'User Minus'), ('FaUserEdit', 'User Edit'), ('FaUserCog', 'User Cog'), ('FaUserShield', 'User Shield'), ('FaUserSecret', 'User Secret'), ('FaUserGraduate', 'User Graduate'), ('FaUserTie', 'User Tie'), ('FaUserNurse', 'User Nurse'), ('FaUserMd', 'User MD'), ('FaUserInjured', 'User Injured'), ('FaUserFriends', 'User Friends'), ('FaUserClock', 'User Clock'), ('FaUserTag', 'User Tag'), ('FaUserSlash', 'User Slash'), ('FaUsers', 'Users'), ('FaUsersCog', 'Users Cog'), ('FaUserCircle', 'User Circle'), ('FaIdCard', 'ID Card'), ('FaIdCardAlt', 'ID Card Alt'), ('FaAddressCard', 'Address Card'), ('FaAddressBook', 'Address Book'), ('FaPhoneAlt', 'Phone Alt'), ('FaPhoneSquare', 'Phone Square'), ('FaPhoneSquareAlt', 'Phone Square Alt'), ('FaPhoneVolume', 'Phone Volume'), ('FaPhoneSlash', 'Phone Slash'), ('FaEnvelopeOpen', 'Envelope Open'), ('FaEnvelopeSquare', 'Envelope Square')], default='FaImages', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gallery_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'db_table': 'gallery_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('location', models.CharField(blank=True, help_text='Location where photo was taken', max_length=100, null=True)),
                ('date_taken', models.DateField(blank=True, help_text='Date when photo was taken', null=True)),
                ('photographer', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured images appear prominently')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.gallerycategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'gallery_images',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='accounts.galleryimage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image View',
                'verbose_name_plural': 'Gallery Image Views',
                'db_table': 'gallery_image_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='accounts.galleryimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image Like',
                'verbose_name_plural': 'Gallery Image Likes',
                'db_table': 'gallery_image_likes',
                'unique_together': {('image', 'user')},
            },
        ),
    ]
