# Generated by Django 5.0.6 on 2025-09-27 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gallerycategory_galleryimage_galleryimageview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(default='month', help_text='per month, per semester, etc.', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('distance_from_campus', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_min', models.PositiveIntegerField(default=1)),
                ('capacity_max', models.PositiveIntegerField(default=1)),
                ('capacity_description', models.CharField(blank=True, max_length=100, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='accommodation_images/')),
                ('image_gallery', models.JSONField(blank=True, default=list, help_text='List of additional image URLs')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('full', 'Full'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature descriptions')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenity codes')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of highlight tags')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'db_table': 'accommodations',
                'ordering': ['-is_featured', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing_scheduled', 'Viewing Scheduled'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('closed', 'Closed')], default='new', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='accounts.accommodation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accommodation Inquiry',
                'verbose_name_plural': 'Accommodation Inquiries',
                'db_table': 'accommodation_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(choices=[('FaBuilding', 'Building'), ('FaHome', 'Home'), ('FaBed', 'Bed'), ('FaKey', 'Key'), ('FaHotel', 'Hotel'), ('FaUniversity', 'University'), ('FaSchool', 'School'), ('FaUsers', 'Users'), ('FaUser', 'Single User'), ('FaUserFriends', 'Multiple Users'), ('FaMapMarkerAlt', 'Location'), ('FaCar', 'Car'), ('FaWifi', 'WiFi'), ('FaUtensils', 'Kitchen'), ('FaShower', 'Bathroom'), ('FaParking', 'Parking'), ('FaSwimmingPool', 'Swimming Pool'), ('FaGamepad', 'Gym'), ('FaTree', 'Garden'), ('FaSun', 'Air Conditioning'), ('FaShieldAlt', 'Security'), ('FaHeart', 'Heart'), ('FaStar', 'Star'), ('FaCheck', 'Check'), ('FaTimes', 'Times')], default='FaBuilding', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accommodation Type',
                'verbose_name_plural': 'Accommodation Types',
                'db_table': 'accommodation_types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='accounts.accommodationtype'),
        ),
        migrations.CreateModel(
            name='AccommodationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accommodation Review',
                'verbose_name_plural': 'Accommodation Reviews',
                'db_table': 'accommodation_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('accommodation', 'user')},
            },
        ),
    ]
