# Generated by Django 5.0.6 on 2025-10-08 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('occupation', models.BooleanField(default=False, help_text='Currently employed?')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('jhs', 'Junior High School'), ('shs', 'Senior High School'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('telephone_number', models.CharField(max_length=20)),
                ('guarantee_name', models.CharField(max_length=100)),
                ('guarantee_number', models.CharField(max_length=20)),
                ('student_photo', models.ImageField(blank=True, help_text='Upload student photo', null=True, upload_to='student_photos/')),
                ('valid_card_photo', models.ImageField(blank=True, help_text='Upload photo of valid ID card', null=True, upload_to='student_cards/')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
    ]
