# Generated by Django 5.0.6 on 2025-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Registration', 'verbose_name_plural': 'Student Registrations'},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
