# Generated by Django 5.0.6 on 2025-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero banner image for category detail page', null=True, upload_to='category_heroes/'),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero banner image for course detail page', null=True, upload_to='course_heroes/'),
        ),
    ]
